apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: navidrome-hpa
  namespace: navidrome-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: navidrome
  minReplicas: 1
  maxReplicas: 2
  metrics:
    # Scale up if CPU exceeds 80%
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    # Scale up if memory exceeds 85%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max
