---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serve-artifacts-pvc
  namespace: navidrome-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome-serve
  namespace: navidrome-platform
  labels:
    app: navidrome-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome-serve
  template:
    metadata:
      labels:
        app: navidrome-serve
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: serve
          image: registry.kube-system.svc.cluster.local:5000/navidrome-serve:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MLFLOW_TRACKING_URI
              value: ""
            - name: VOCAB_PATH
              value: "/app/artifacts/vocabs.pkl"
            - name: MODEL_PATH
              value: "/app/artifacts/best_gru4rec.pt"
            - name: DEVICE
              value: "cpu"
            - name: MINIO_URL
              value: "http://minio.navidrome-platform.svc.cluster.local:9000"
            - name: MINIO_USER
              value: "minioadmin"
            - name: MINIO_PASSWORD
              value: "navidrome2026"
            - name: MINIO_BUCKET
              value: "artifacts"
            - name: MINIO_POPULARITY_KEY
              value: "popularity.npy"
            - name: TRACK_META_BUCKET
              value: "navidrome-metadata"
            - name: TRACK_META_KEY
              value: "track_dict.parquet"
            - name: AUDIO_BUCKET
              value: "audio-cache"
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: serve-artifacts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome-serve
  namespace: navidrome-platform
  labels:
    app: navidrome-serve
spec:
  selector:
    app: navidrome-serve
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
