apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-navidrome-custom
  namespace: argo
spec:
  entrypoint: build-flow

  podMetadata:
    annotations:
      seccomp.security.alpha.kubernetes.io/pod: unconfined
      container.apparmor.security.beta.kubernetes.io/main: unconfined

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

  volumes:
  - name: buildkitd
    emptyDir: {}

  templates:
  - name: build-flow
    steps:
      - - name: clone-fork
          template: git-clone
      - - name: build-and-push
          template: buildkit-rootless

  - name: git-clone
    retryStrategy:
      limit: "3"
      retryPolicy: "Always"
      backoff:
        duration: "10s"
        factor: "2"
    container:
      image: alpine/git:v2.26.2
      workingDir: /mnt/workspace
      command: [git]
      args:
        - clone
        - --depth
        - "1"
        - --single-branch
        - --branch
        - navidrome-custom
        - https://github.com/yeshavyas27/navidrome_mlops.git
        - .
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: buildkit-rootless
    retryStrategy:
      limit: "2"
      retryPolicy: "Always"
      backoff:
        duration: "30s"
        factor: "2"
    container:
      image: moby/buildkit:rootless
      env:
      - name: BUILDKITD_FLAGS
        value: --oci-worker-no-process-sandbox
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "6Gi"
          cpu: "4"
      command: [buildctl-daemonless.sh]
      args:
        - build
        - --frontend
        - dockerfile.v0
        - --local
        - context=/mnt/workspace
        - --local
        - dockerfile=/mnt/workspace
        - --output
        - type=image,name=registry.kube-system.svc.cluster.local:5000/navidrome-custom:latest,push=true,registry.insecure=true
        - --export-cache
        - type=registry,ref=registry.kube-system.svc.cluster.local:5000/navidrome-custom:buildcache,mode=max,registry.insecure=true
        - --import-cache
        - type=registry,ref=registry.kube-system.svc.cluster.local:5000/navidrome-custom:buildcache,registry.insecure=true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: Unconfined
        appArmorProfile:
          type: Unconfined
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace
      - name: buildkitd
        mountPath: /home/user/.local/share/buildkit
